-- V16: store user reports of offensive/inappropriate group content (member, shared photo, or task).
-- Required by Google Play's user-generated-content policy: members must be able to report content
-- shared by other members. Reports land here for manual moderation review. Blocking a user is
-- handled client-side (device-local), so only reports are persisted server-side.

CREATE TABLE IF NOT EXISTS content_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES family_groups (id) ON DELETE CASCADE,
    target_type VARCHAR(16) NOT NULL,
    target_user_id BIGINT,
    target_ref VARCHAR(512),
    reason VARCHAR(500),
    target_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- One report per (reporter, target): re-reporting the same target is a no-op (server-side dedup).
CREATE UNIQUE INDEX IF NOT EXISTS idx_content_reports_reporter_hash ON content_reports (reporter_user_id, target_hash);
CREATE INDEX IF NOT EXISTS idx_content_reports_created_at ON content_reports (created_at);
