-- V21: append-only audit trail for every administrative write (suspend, delete, push, report
-- resolution, settings change). An admin surface that can delete accounts must be able to answer
-- "who did this, when, from where" after the fact.
--
-- actor_user_id has deliberately NO foreign key and actor_email is denormalized: the audit record has
-- to outlive the actor. If an admin account is ever deleted, its history must remain readable rather
-- than cascade away — which is exactly the case where the log matters most.
--
-- request_id mirrors the MDC value CorrelationIdFilter already stamps on every log line and echoes as
-- the X-Request-Id response header, so an audit row cross-references the raw request logs.

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    actor_email VARCHAR(255) NOT NULL,
    action VARCHAR(48) NOT NULL,
    target_type VARCHAR(24),
    target_id VARCHAR(64),
    detail VARCHAR(1000),
    request_id VARCHAR(64),
    ip VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created_at ON admin_audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_admin_audit_actor ON admin_audit_log (actor_user_id, created_at);
