-- V30: one row per pomodoro interval, raw. Not a daily rollup.
--
-- Aggregates are computed live over these rows, like every other number on the admin surface (see the
-- MetricsQueryRepository header): a nightly rollup on a single Render instance permanently loses a day
-- whenever a deploy lands in that window, and the hole in history cannot be recomputed afterwards.
--
-- `completed` together with elapsed_seconds is the whole point of this table. A pomodoro abandoned six
-- minutes into twenty-five and one that ran the full length are different facts, and recording only the
-- second would make the product look as though every session succeeded. Every focus-time figure sums
-- elapsed_seconds; nothing sums planned_seconds — that is the time the app offered, not the time the
-- user actually spent.
--
-- Two clocks, deliberately. `ended_at` is an instant, and every admin aggregate chases it in UTC like
-- the rest of that surface. `local_date` is the epoch day in the *device's* time zone — what the in-app
-- statistics screen groups by, and what the client downloads back at sign-in. Without it an Istanbul
-- user's 01:30 session shifts to the previous day the moment it round-trips through the server.
-- task_daily_completions carries the same pair for the same reason.
--
-- `client_session_id` is a client-generated idempotency key, the same shape as tasks.client_task_id: a
-- retried batch upload dedupes on the unique index instead of doubling the user's focus time.
-- `client_run_id` groups the intervals of a single sitting.
--
-- `mode` is a VARCHAR rather than a constrained type so the reserved 'OVERTIME' value can arrive with a
-- client release and no migration. Every aggregate filters mode explicitly for exactly that reason.
--
-- Identity is GENERATED BY DEFAULT AS IDENTITY, not BIGSERIAL: the standard spelling parses on both
-- Postgres 10+ and H2, which is what keeps this file byte-identical in the two migration directories.
-- V7 predates that and is one of the pairs that had to diverge.
--
-- Retention is 24 months, promised in the privacy policy. The rows are immutable and independent of one
-- another, so the delete is a plain range scan on ended_at — the index below already serves it.

CREATE TABLE IF NOT EXISTS pomodoro_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_session_id VARCHAR(36) NOT NULL,
    client_run_id     VARCHAR(36) NOT NULL,
    session_index     INT         NOT NULL DEFAULT 0,
    mode              VARCHAR(16) NOT NULL,
    planned_seconds   INT         NOT NULL,
    elapsed_seconds   INT         NOT NULL,
    completed         BOOLEAN     NOT NULL,
    started_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    local_date        BIGINT      NOT NULL,
    tz_offset_minutes INT
);

-- Idempotency. A retried upload lands here rather than on a second row.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pomodoro_sessions_owner_client
    ON pomodoro_sessions (user_id, client_session_id);

-- Sign-in backfill: the client asks in its own calendar, so this is the index that serves it.
CREATE INDEX IF NOT EXISTS idx_pomodoro_sessions_user_local_date
    ON pomodoro_sessions (user_id, local_date);

-- The admin daily series scans by date across all users; the index above is user-first and cannot serve
-- it. Retention pruning uses this one too.
CREATE INDEX IF NOT EXISTS idx_pomodoro_sessions_ended_at
    ON pomodoro_sessions (ended_at);
