-- V13: store user reports of offensive/inappropriate DoneBot (AI) replies.
-- Required by Google Play's Generative AI policy: users must be able to flag
-- AI-generated content in-app. Reports land here for manual moderation review.

CREATE TABLE IF NOT EXISTS chat_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message_content VARCHAR(4000) NOT NULL,
    message_hash VARCHAR(64) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- One report per (user, reply): a user re-flagging the same reply text is a no-op (server-side dedup).
CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_reports_user_hash ON chat_reports (user_id, message_hash);
CREATE INDEX IF NOT EXISTS idx_chat_reports_created_at ON chat_reports (created_at);
